language: ruby
rvm:
- 2.5.3
bundler_args: --jobs=2
script:
  - bundle exec rails db:{create,migrate} RAILS_ENV=test
  - bundle exec rspec
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.6"
